name: Verify

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Check For Lint
        run: npm run lint

      - name: Run Unit Tests + Coverage
        run: yarn test:cov

      - name: Run Build
        run: yarn build

      - name: Upload Coverage
        env:
          CODE_COV: ${{ secrets.CODE_COV }}
        # Upload to codecov.io. Curl used in place of codecov/codecov-action
        # due to long build time. See https://github.com/codecov/codecov-action/issues/21
        run: curl -s https://codecov.io/bash | bash -s -- -t $CODE_COV
